### ISSUE TITLE
Q: How Selene compares to Boost.GIL

### ISSUE THREAD

**Issue by mloskot** [kmhofmann/selene#1]
Question: would be able to provide brief comparison on how Selene is similar/different to [Boost.GIL](http://www.boost.org/doc/libs/release/libs/gil/)?

A similar reference as you make to OpenCV in the Rationale document would be helpful for prospect users considering Selene.

**Comment by kmhofmann** [comment]
Hi @mloskot, commit https://github.com/kmhofmann/selene/commit/fe47112ae00f714878812211edb325972c5315fd adds a brief comparison to GIL.

**Comment by mloskot** [comment]
@kmhofmann thank you!
