### ISSUE TITLE
Add includes to example in README

### ISSUE THREAD

**Issue by shrinktofit** [kmhofmann/selene#4]
And I can't find `PixelRGB_8u`...

**Comment by kmhofmann** [comment]
Hi @shrinktofit, thanks for using Selene. The example contained in the README.md file is fully reproduced here, including all includes:
https://github.com/kmhofmann/selene/blob/master/examples/readme_example.cpp

When you build all examples using the "-DSELENE_BUILD_EXAMPLES=ON" CMake option, this file will also be built. You can find further instructions on how to build Selene here:
https://github.com/kmhofmann/selene/blob/master/docs/building.md

The type alias sln::PixelRGB_8u is defined here:
https://github.com/kmhofmann/selene/blob/master/selene/img/PixelTypeAliases.hpp#L79
