### ISSUE TITLE
Some deprecated function

### ISSUE THREAD

**Issue by shrinktofit** [kmhofmann/selene#5]
`FileReader.hpp` use function `fopen` and `strerror`, these functions are marked as deprecated in MSVC(for me, Visual Studio 2017). It requires a definition of macro `_CRT_SECURE_NO_WARNINGS` or use the suggested `fopen_s` or `strerror_s`. Why don't you choose `std::ifstream?`

**Comment by kmhofmann** [comment]
The C API is used for performance reasons. Visual C++ is the only compiler that I know of that "warns" about these functions. Note that they are *not* deprecated by the ISO C++ standard; technically, Visual C++ is wrong.

When building with CMake, the preprocessor definition you mention is indeed set; see here:
https://github.com/kmhofmann/selene/blob/master/cmake/compiler_options.cmake
Selene should build warning-free.

See here for more information how to build Selene using CMake:
https://github.com/kmhofmann/selene/blob/master/docs/building.md

Alternatively, it should be possible to install a released version of Selene using vcpkg; see here:
https://github.com/kmhofmann/selene/blob/master/docs/installation.md

**Comment by shrinktofit** [comment]
> Alternatively, it should be possible to install a released version of Selene using vcpkg; see here:
> https://github.com/kmhofmann/selene/blob/master/docs/installation.md

The errors appeared when using the vcpkg.

I disable this warning by add include directive:
```cpp
#ifdef _MSC_VER
#pragma warning(disable:4996)
#endif
#include <selene/img_io/IO.hpp>
```

**Comment by kmhofmann** [comment]
Yep, you're right. Can you double check if the changes made in https://github.com/kmhofmann/selene/commit/35264eb9439bd0234188543d3a20c9156c3af6c3 fix all the warnings, after removing the pragma in your client code again? I can't test behavior on Windows right now, but I think this should work.

**Comment by shrinktofit** [comment]
It works for me. Thx

**Comment by kmhofmann** [comment]
Merged. https://github.com/kmhofmann/selene/pull/6
